services:
  - type: web
    name: creators-hub-backend
    env: node

    buildCommand: npm run build

    startCommand: npx prisma db push && npm start

    envVars:
      - key: DATABASE_URL
        sync: false

      - key: JWT_SECRET
        sync: false

      - key: FRONTEND_URL
        sync: false

      - key: NODE_VERSION
        value: 22
